/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.awt.image.BufferedImage;
import javax.imageio.ImageIO;

public class App {
    public static void main(String[] args) throws IOException {
        if (args.length < 3) {
            System.out.println("Please use: <input-file-path> <output-file-path> <transform-name>");
            return;
        }

        String inputFilePath = args [0];
        String outputFilePath = args[1];
        String transformName = args[2];

        Bitmap bitmap = new Bitmap(inputFilePath);

        switch (transformName.toLowerCase()) {
            case "invert":
                bitmap.invertColors(outputFilePath);
                break;
            case "randomize":
                bitmap.randomizeColors(outputFilePath);
                break;
            case "darken":
                bitmap.darkenColors(outputFilePath);
                break;
            default:
                System.out.println("Available options: invert, randomize, darken");
                break;

        }
        for (int i = 0; i < args.length; i++) {
            System.out.println(args[i]);

        }
    }
}

        // We need 3 passable arguements that we will be able to run via the command line into the Public Static Void Main(String[] args)
        // To do this we will need: input-file-path, output-file-path, transform-name (Invert, Randomize, Darken)
//        The CLI should support a minimum of three transforms, each of which is an instance method in the Bitmap class.
//        The CLI should log useful Error messages if used incorrectly.
//        The CLI should log a success message on completion.
        // 3 classes of Bitmap that can be called in the App.main with String[] args
        // The end result should be a new file (ex:Invert.bmp) placed into the resources folder located at app/src/main/resources


//        wheretogo resourcefolderpath Invert
